POST http://localhost/storystream/api/registration.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user_email=namcccmmccce2@tecccst.com&user_name=se1xxncnccan&user_pass=someDecentPassword

### GET Format

GET http://localhost/storystream/api/registration.php?user_email=shan@test.com&user_name=sean&user_pass=someDecentPass

###

POST http://localhost/storystream/api/signin.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user_name=&user_pass=hj

###

POST http://localhost/storystream/api/forgotpassword.php HTTP/1.1
content-type: application/x-www-form-urlencoded
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNTQifQ.ym5VdSy7FHIxC2hO-J-u96DAzf6wEYRQV5dyIvm8Zeg

###

POST http://localhost/storystream/api/resetpassword.php HTTP/1.1
content-type: application/x-www-form-urlencoded
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNjAifQ.3Ein9pNvFMTyIFIN7xHRzx4dwjv2TG2LtKL9lBnFUGk

user_pass=hj&user_new_pass=kldd

###

POST http://localhost/storystream/api/forgotpassword.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user_email=&user_pass=
