POST http://localhost/storystream/registration.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user_email=name2@test.com&user_name=se1ncnan&user_pass=someDecentPassword

### GET Format

GET http://localhost/storystream/registration.php?user_email=shan@test.com&user_name=sean&user_pass=someDecentPass

###

POST http://localhost/storystream/signin.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user_name=se1ncnan&user_pass=someDecentPassword

###

POST http://localhost/storystream/forgotpassword.php HTTP/1.1
content-type: application/x-www-form-urlencoded
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNTQifQ.ym5VdSy7FHIxC2hO-J-u96DAzf6wEYRQV5dyIvm8Zeg

###

POST http://localhost/storystream/resetpassword.php HTTP/1.1
content-type: application/x-www-form-urlencoded
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNjEifQ.v_0gTv6kQq48EHuKpyz23clb9gLf7JT1CHkPtPx-_Is

user_pass=someDecentPassword&user_new_pass=kl

###

POST http://localhost/storystream/forgotpassword.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded

user_email=&user_pass=
